name: Check Tiny Models
on:
  push:
    branches:
    - fix_tiny_to_make_everyone_LOVE_it
  repository_dispatch: null
  schedule:
  - cron: 0 2 * * *
env:
  TOKEN: ${{ secrets.TRANSFORMERS_HUB_BOT_HF_TOKEN }}
  HF_TOKEN: ${{ secrets.HF_HUB_READ_TOKEN }}
jobs:
  check_tiny_models:
    name: Check tiny models
    runs-on: ubuntu-latest
    steps:
    - name: Checkout transformers
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install
      run: 'sudo apt-get -y update && sudo apt-get install -y libsndfile1-dev espeak-ng
        cmake

        pip install --upgrade pip

        python -m pip install -U .[dev]

        '
    - name: Create all tiny models (locally)
      run: 'python utils/create_dummy_models.py tiny_local_models --all --num_workers
        1

        '
    - name: Local tiny model reports artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: tiny_local_model_creation_reports
        path: tiny_local_models/reports
