name: Build PR Documentation
on:
  pull_request_target: null
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  remind:
    name: remind
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Install requirements
      run: 'echo "Bonjour"

        '
