name: Nvidia CI with nightly torch
on:
  repository_dispatch: null
  workflow_run:
    workflows:
    - Nvidia CI
    branches:
    - main
    types:
    - completed
  push:
    branches:
    - trigger_ci_with_torch_2.9.1_rc_commit_8012f80f722044fd0dda45b4034f89fffc2ff344
env:
  prev_workflow_run_id: '19156555083'
  other_workflow_run_id: ''
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: 'mkdir "setup_values"

        echo "${{ inputs.prev_workflow_run_id || env.prev_workflow_run_id }}" > "setup_values/prev_workflow_run_id.txt"

        echo "${{ inputs.other_workflow_run_id || env.other_workflow_run_id }}" >
        "setup_values/other_workflow_run_id.txt"

        '
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: setup_values
        path: setup_values
  model-ci:
    name: Model CI
    uses: ./.github/workflows/self-scheduled.yml
    with:
      job: run_models_gpu
      slack_report_channel: '#transformers-ci-dummy'
      docker: huggingface/transformers-all-latest-torch-nightly-gpu
      ci_event: Nightly CI
      runner_type: a10
      report_repo_id: hf-internal-testing/transformers_daily_ci_with_torch_nightly
      commit_sha: ${{ github.event.workflow_run.head_sha || github.sha }}
    secrets: inherit
